# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{right_aws}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Tadman"]
  s.date = %q{2010-11-08}
  s.description = %q{RightAws gem patched for Rails 3}
  s.email = %q{info@twg.ca}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "lib/acf/right_acf_interface.rb",
     "lib/acf/right_acf_origin_access_identities.rb",
     "lib/acf/right_acf_streaming_interface.rb",
     "lib/acw/right_acw_interface.rb",
     "lib/as/right_as_interface.rb",
     "lib/awsbase/benchmark_fix.rb",
     "lib/awsbase/right_awsbase.rb",
     "lib/awsbase/support.rb",
     "lib/ec2/right_ec2.rb",
     "lib/ec2/right_ec2_ebs.rb",
     "lib/ec2/right_ec2_images.rb",
     "lib/ec2/right_ec2_instances.rb",
     "lib/ec2/right_ec2_monitoring.rb",
     "lib/ec2/right_ec2_reserved_instances.rb",
     "lib/ec2/right_ec2_security_groups.rb",
     "lib/ec2/right_ec2_spot_instances.rb",
     "lib/ec2/right_ec2_vpc.rb",
     "lib/elb/right_elb_interface.rb",
     "lib/rds/right_rds_interface.rb",
     "lib/right_aws.rb",
     "lib/s3/right_s3.rb",
     "lib/s3/right_s3_interface.rb",
     "lib/sdb/active_sdb.rb",
     "lib/sdb/right_sdb_interface.rb",
     "lib/sqs/right_sqs.rb",
     "lib/sqs/right_sqs_gen2.rb",
     "lib/sqs/right_sqs_gen2_interface.rb",
     "lib/sqs/right_sqs_interface.rb",
     "right_aws.gemspec",
     "test/acf/test_helper.rb",
     "test/acf/test_right_acf.rb",
     "test/awsbase/test_helper.rb",
     "test/awsbase/test_right_awsbase.rb",
     "test/ec2/test_helper.rb",
     "test/ec2/test_right_ec2.rb",
     "test/http_connection.rb",
     "test/rds/test_helper.rb",
     "test/rds/test_right_rds.rb",
     "test/s3/test_helper.rb",
     "test/s3/test_right_s3.rb",
     "test/s3/test_right_s3_stubbed.rb",
     "test/sdb/test_active_sdb.rb",
     "test/sdb/test_batch_put_attributes.rb",
     "test/sdb/test_helper.rb",
     "test/sdb/test_right_sdb.rb",
     "test/sqs/test_helper.rb",
     "test/sqs/test_right_sqs.rb",
     "test/sqs/test_right_sqs_gen2.rb",
     "test/test_credentials.rb",
     "test/ts_right_aws.rb"
  ]
  s.homepage = %q{http://github.com/twg/right_aws}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RightAws gem patched for Rails 3}
  s.test_files = [
    "test/acf/test_helper.rb",
     "test/acf/test_right_acf.rb",
     "test/awsbase/test_helper.rb",
     "test/awsbase/test_right_awsbase.rb",
     "test/ec2/test_helper.rb",
     "test/ec2/test_right_ec2.rb",
     "test/http_connection.rb",
     "test/rds/test_helper.rb",
     "test/rds/test_right_rds.rb",
     "test/s3/test_helper.rb",
     "test/s3/test_right_s3.rb",
     "test/s3/test_right_s3_stubbed.rb",
     "test/sdb/test_active_sdb.rb",
     "test/sdb/test_batch_put_attributes.rb",
     "test/sdb/test_helper.rb",
     "test/sdb/test_right_sdb.rb",
     "test/sqs/test_helper.rb",
     "test/sqs/test_right_sqs.rb",
     "test/sqs/test_right_sqs_gen2.rb",
     "test/test_credentials.rb",
     "test/ts_right_aws.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<right_http_connection>, [">= 0"])
    else
      s.add_dependency(%q<right_http_connection>, [">= 0"])
    end
  else
    s.add_dependency(%q<right_http_connection>, [">= 0"])
  end
end

